<?php

spl_autoload_register(function ($className){
    $className = str_replace("\\", "/", $className);

    require_once ("lib/$className.php");
});

/*// autoload.php @generated by Composer

if (PHP_VERSION_ID < 50600) {
    echo 'Composer 2.3.0 dropped support for autoloading on PHP <5.6 and you are running '.PHP_VERSION.', please upgrade PHP or use Composer 2.2 LTS via "composer self-update --2.2". Aborting.'.PHP_EOL;
    exit(1);
}

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit15db72d0779e0f40868fbda593b67434::getLoader();*/